### ISSUE TITLE
0 bytes generated

### ISSUE THREAD

**Issue by kenjibailly** [hotio/stash#1]
Everything installs nicely, but once in the web UI I cannot seem to generate content.
I have tried to change the permissions of the folder, generating in the tasks, reloading the scrapers.

Installed with latest docker image.

![image](https://user-images.githubusercontent.com/9883910/107070370-8ade6580-67e3-11eb-8ff2-6eaca384fa80.png)

**Comment by mrhotio** [comment]
I'm sorry, not real familiar with how to correctly setup this app.

**Comment by mrhotio** [comment]
If you need any more support, join the discord server, or if you figure out what went wrong and it's something I can alleviate, please let me know. Closing the issue for now.
