### ISSUE TITLE
ffmpeg is missing encoder 

### ISSUE THREAD

**Issue by lepis0** [hotio/stash#2]
When generating previews ffmpeg gives next error:
`ffmpeg error when running command </config/.stash/ffmpeg -v error -i /data/transcode/screenshots/6550225faebce56d.mp4 -y -c:v libwebp -lossless 1 -q:v 70 -compression_level 6 -preset default -loop 0 -threads 4 -vf scale=640:-2,fps=12 -an /data/transcode/tmp/6550225faebce56d.webp>: Unknown encoder 'libwebp'`

**Comment by mrhotio** [comment]
I'm aware of this, but I've been told that they don't recommend the use of webp and that it might go away....so I didn't look into it further
